spring:
  application:
    name: order-service

  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/wellenceApiDb
    username: wellence_dev
    password: Ifeomimi2024
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      group-id: wellence_api
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 0
logging:
  level:
    org:
      springframework:
       security: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
